### PR TITLE
Add multiline literal aligned with bar

### PR DESCRIPTION
**Pull request by junjihashimoto**
Add multiline literal aligned with bar.
This is inspired by heredoc of hackage.

### CODE REVIEW

**Comment by snoyberg** [comment]
This looks good to me, I just have one question: why does the output (at least in the test) include `\r` characters?

This may be obvious, I'm just not fully awake right now.

**Comment by junjihashimoto** [comment]
It is because the test file(TextSpec.hs) is DOS format whose newline is "\r\n".
I was surprised too.

**Comment by snoyberg** [comment]
Cool, thanks!

**Comment by junjihashimoto** [comment]
Thanks too.

**Pull request merged**
