### PR TITLE
add missing html5 void elements

### PR DESCRIPTION
**Pull request by rkaminsk**
see #184

### CODE REVIEW

**Comment by psibi** [comment]
@rkaminsk Can you also add a link to the specification as a comment on top of `htmlEmptyTags` ?

**Comment by rkaminsk** [comment]
The patch should be complete now. I also added the link to the relevant section of the w3c html 5 specification. It looks like there are already new void elements coming in html 5.1. Since it is just a working draft, I did not add the tags.

**Comment by psibi** [comment]
LGTM. I will let others review before merge.

**Comment by psibi** [comment]
I will merge this if there is no objection. CC: @snoyberg

**Comment by snoyberg** [comment]
No objection from me

**Pull request merged**
