### PR TITLE
Escape single quote in Julius variable interpolation

### PR DESCRIPTION
**Pull request by pythonissam**

### CODE REVIEW

**Comment by pythonissam** [comment]
issue ref: https://github.com/yesodweb/yesod/issues/1547

**Comment by snoyberg** [comment]
Code looks good. Can you add a ChangeLog entry and a cabal file version bump?

**Comment by pythonissam** [comment]
Is my versioning correct? My commit changed pre-exists function's behavior, so I bumped the second major version number from the left

**Comment by snoyberg** [comment]
Even though it changes behavior, it changes behavior in a way that is semantically matching, so I'd make it a minor version bump (third component).

**Comment by pythonissam** [comment]
@snoyberg Done! Is this okay?

**Comment by pythonissam** [comment]
Yay! Thank you too!

**Pull request merged**
