### PR TITLE
added: parse pattern-match with operator constructor closed #222

### LINKED ISSUE #222: Constructor for lists `(:)` does not work in hamlet template
The next code snippet 

```
$case [1, 2, 3]
   $of x:xs
      #{x}
      $forall y <- xs
         , #{y}
```
causes an error:
```
unexpected ":"
expecting letter or digit, "_", "'", " ", "@", "," or ")"
```
The pattern of empty list [] is supported, but the support for compound list constructor (:) is not. Is it a bug or a feature? It is possible to make a workaround, using `$if` clause, but the case pattern seems to be more natural here.

### PR DESCRIPTION
**Pull request by ncaq**
I do not think beautiful code.
However I check to pass test.
Is there a possibility that this code creates a bug?

### CODE REVIEW

**Comment by ncaq** [comment]
This pull request to fix bug #222

**Comment by ncaq** [comment]
test is timeout and network error.
I retry travis.

**Comment by ncaq** [comment]
@snoyberg I bumped version.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
