### PR TITLE
Use varExp function.

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
@snoyberg 

I have been going through the shakespeare code and found this [FIXME comment](https://github.com/yesodweb/shakespeare/blob/511f9e309f7f3f76b7f7a41d3bab6f4896b55a12/Text/MkSizeType.hs#L42) (git blame tells me you wrote it) related to the patch. Unfortunately, the FIXME comment there in the original code doesn't tell me what makes you nervous. Following my intuition, I have fixed it up. Let me know if this patch doesn't address your concerns. :)

**Comment by snoyberg** [comment]
Thanks :). IIRC, my concern was that this will only work if the identifiers are in scope at the call site. The simplest solution is just to use syntax like `'fromLazyText`.

**Comment by psibi** [comment]
Thanks, does the `'` symbol before `fromLazyText` signify something ?

**Comment by snoyberg** [comment]
It's the method of quoting names for template Haskell. See
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/template-haskell.html

**Comment by psibi** [comment]
Thanks, will look into this.

**Comment by psibi** [comment]
@snoyberg I have updated the patch. I will merge this if you are ok with it. The only main difference is I'm using `fmap` instead of `.` as `'Prelude..` or it's variations doesn't compile. I will paste the [commit message](https://github.com/psibi/shakespeare/commit/2a859df0124b4675a6ae4d153462872c77a81935) here for more clarity:

````
Note that I'm using fmap instead of (.) as 'Prelude.. doesn't typecheck.
The generated code looks like this now:

toCss = fmap Data.Text.Internal.Builder.fromLazyText (fmap TL.pack show)

which is equivalent to the earlier generated code:

toCss = (.) fromLazyText ((.) TL.pack show)
````

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
