### PR TITLE
Some test organization

### PR DESCRIPTION
**Pull request by chreekat**
Most controversial(?) is converting to LF line endings. Otherwise:

1. Made specs match module names (Text.Shakespeare.Foo -> Text.Foo)
2. Removed unnecessary extra top-level 'describe' (since hspec-discover already provides one)

### CODE REVIEW

**Comment by snoyberg** [comment]
Actually, IIRC, the line endings were purposely done this way to force testing of CRLF line endings in templates, since there were a number of bugs there. As strange/annoying as it is, I'd rather leave it as-is.

**Comment by chreekat** [comment]
Ahhh, ok. One sec...

**Comment by chreekat** [comment]
I rebased and started things off by adding a .gitattributes, which let me keep the crlf:s without getting a bunch of funny characters in the diff.

**Comment by chreekat** [comment]
Actually... is that now normalizing it (making it LF in the database)? Let me try something..

**Comment by chreekat** [comment]
No, I think this is actually what I want. I was momentarily distracted by the diff still being huge, but that's just the consequence of moving the file.

**Comment by snoyberg** [comment]
Awesome. And just to confirm and avoid a lot of busywork review: am I correct in understanding that besides the module name, you changed none of the content in the modules themselves when you renamed the files?

**Comment by chreekat** [comment]
That's correct.

**Comment by chreekat** [comment]
Unfortunately I just noticed that the original HamletSpec did *not* have crlf line endings, unlike the other specs. I can switch it back if necessary.

**Comment by snoyberg** [comment]
I'm OK with the change, thanks!

**Pull request merged**
