### PR TITLE
Markdown support (marcus)

### PR DESCRIPTION
**Pull request by chreekat**
This is a work in progress. The proposal is to add "marcus" as a Markdown processor, using [snoyberg/markdown](https://github.com/snoyberg/markdown). I'm basing the implementation on CoffeeScript support, since all I want is a pre-conversion and then variable interpolation.

I'm currently just adding some more tests and so forth.

Feedback appreciated.

### CODE REVIEW

**Comment by chreekat** [comment]
I should mention that the current diff is way out of date and nonsensical. Looks like I have some rather important things in `git stash`... :P

**Comment by chreekat** [comment]
Now it's more in line with what I actually want to merge. Still have some tests and refactoring left, though.

**Comment by snoyberg** [comment]
This is great, and something I (and others) have wanted for a while. However, I'm not sure that using the markdown package is a good idea, as cmark may be better.

There's also a question of growing the dependency list for shakespeare, so there may be some general objection to adding this.

**Comment by chreekat** [comment]
Maybe I should instead make any necessary modifications to shakespeare and use it as a dependency to a new shakespeare-markdown package?

I don't want to use pandoc for the same reason (dependency list), but I have a hard requirement to provide support for footnotes. Since CommonMark doesn't have them yet, I think I'll be sticking with markdown. Hence the related discussion over on that package.

**Comment by snoyberg** [comment]
I think a separate package may be the best bet for now, yes.

**Comment by chreekat** [comment]
Closing in favor of creating a new package.

**Pull request closed without merging**
