### PR TITLE
Handle expressions with infix operator and trailing spaces

### PR DESCRIPTION
**Pull request by arowM**
This should fix the unnatural behaviour mentioned in #211.

### CODE REVIEW

**Comment by psibi** [comment]
Thanks for the PR. If possible can you also add a test case for this ?

**Comment by arowM** [comment]
OK. Where is the best place to add test case for this?
Is it supposed to add test cases for `parseDeref` newly on `test/Text/ShakeSpeare/BaseSpec.hs`?

**Comment by psibi** [comment]
@arowM Yes, that seems a fine location to me.

**Comment by arowM** [comment]
I've added a simple test case about this issue.

**Comment by snoyberg** [comment]
Looks OK to me. @psibi any objections"

@arowM Can you add a minor version bump and update the changelog?

**Comment by arowM** [comment]
I've committed 9f8da95 that updates version and changelog.

**Comment by psibi** [comment]
LGTM. @arowM I think bumping to 2.0.14.1 would be the right thing here. (Ref: https://www.snoyman.com/blog/2017/06/how-to-send-me-a-pull-request)

**Comment by arowM** [comment]
@psibi I see. Thanks.
I've fixed version number and pushed again.

**Comment by psibi** [comment]
Thanks for the PR!

**Comment by psibi** [comment]
@snoyberg Can you give me hackage access for shakespeare so that I can release a new version ? Thanks.

**Comment by snoyberg** [comment]
Done :)

**Comment by psibi** [comment]
Thanks @snoyberg :)

@arowM A new version of shakespeare has been released with your fix. Thanks!

**Pull request merged**
