### PR TITLE
Allow more instances to be exported

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by psibi** [comment]
Is there any specific reason why currently the CPP is being used to restrict the instances ?

Removing the restriction allows me to interpolate value of type `Text` , etc.

**Comment by creichert** [comment]
I believe the idea is to promote checked javascript interpolation by forcing the use of `toJSON`. Otherwise, rawJs can be used.

I believe these were disabled for a reason http://www.yesodweb.com/blog/2012/11/updates-julius-interpolation. I don't necessarily have a problem with exposing these but I'll have to let @snoyberg  or @gregwebs chime in.

**Comment by gregwebs** [comment]
Blog post says it all. The instances should be deleted

**Comment by psibi** [comment]
Thanks for the link, I will look into that.

**Comment by psibi** [comment]
After reading it, it totally makes sense. I have updated the patch to delete those instances.

**Comment by gregwebs** [comment]
Thanks! Glad it makes sense.

**Pull request merged**
